# FreshPlan Team Synchronization

daily_sync:
  time: "09:00 CET"
  duration: "10 min"
  platform: "Slack/Teams"
  agenda:
    - "Blocker?"
    - "API-Änderungen?"
    - "Merge-Readiness?"
    - "Help needed?"
  
weekly_integration:
  time: "Fr 14:00 CET"
  duration: "30 min"
  agenda:
    - "Feature-Demos"
    - "Integration Tests"
    - "Next Sprint Planning"
    - "Tech Debt Review"

team_meetings:
  backend:
    api_review: "Mi 14:00 CET"
    focus: "API Design, Security, Performance"
    
  frontend:
    ui_review: "Do 15:00 CET"
    focus: "UX, Component Library, Accessibility"
    
  testing:
    test_review: "Fr 11:00 CET"
    focus: "Coverage, CI Performance, Test Strategy"

communication:
  channels:
    - "#freshplan-general" # Alle Teams
    - "#freshplan-backend" # Backend Team
    - "#freshplan-frontend" # Frontend Team
    - "#freshplan-testing" # Testing Team
    - "#ci-alerts" # CI/CD Status
    
  escalation:
    - "Team Lead"
    - "Tech Lead"
    - "Project Manager"

merge_windows:
  schedule: "Mo-Do 10:00-16:00 CET"
  requirements:
    - "All CI checks green"
    - "Code review approved"
    - "No merge conflicts"
    - "CHANGELOG updated"