openapi: 3.1.0
info: { title: Leads API (Foundation V2 FIX), version: 1.1.0 }
servers: [ { url: https://api.example.com } ]
security: [ { bearerAuth: [] } ]
components:
  securitySchemes:
    bearerAuth: { type: http, scheme: bearer, bearerFormat: JWT }
  schemas:
    LeadStatus: { type: string, enum: [NEW, ACTIVE, WON, LOST] }
    LeadItem:
      type: object
      properties:
        id: { type: string, format: uuid }
        name: { type: string }
        territory: { type: string }
        status: { $ref: '#/components/schemas/LeadStatus' }
        createdAt: { type: string, format: date-time }
    LeadPage:
      type: object
      properties:
        items:
          type: array
          items: { $ref: '#/components/schemas/LeadItem' }
        nextCursor: { type: string, nullable: true }
    LeadCreateRequest:
      type: object
      required: [name, territory]
      properties:
        name: { type: string, maxLength: 200 }
        territory: { type: string, pattern: '^[A-Z]{2,5}$' }
        status: { $ref: '#/components/schemas/LeadStatus' }
  responses:
    BadRequest: { $ref: ../openapi/common-errors.yaml#/components/responses/BadRequest }
    Forbidden: { $ref: ../openapi/common-errors.yaml#/components/responses/Forbidden }
    Conflict: { $ref: ../openapi/common-errors.yaml#/components/responses/Conflict }
    TooMany: { $ref: ../openapi/common-errors.yaml#/components/responses/TooManyRequests }
paths:
  /api/leads:
    get:
      summary: Leads suchen (ABAC & Named Params, Repository Pattern)
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: { $ref: '#/components/schemas/LeadPage' }
        '403': { $ref: '#/components/responses/Forbidden' }
    post:
      summary: Lead anlegen
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/LeadCreateRequest' }
      responses:
        '201': { description: Created }
        '400': { $ref: '#/components/responses/BadRequest' }
