name: module02-foundation
on: [push]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { distribution: 'temurin', java-version: '17' }
      - run: ./mvnw -B -DskipITs test
      - run: ./mvnw -B -Pcoverage verify
      - run: node --version
      - run: npm ci
      - run: npm run test:ci
      - run: npm run test:e2e
      - name: k6 smoke
        uses: grafana/k6-action@v0.3.1
        with: { filename: k6/leads_performance_test.js }
