openapi: 3.1.0
info: { title: Communication Calls & Meetings API, version: 1.0.0 }
servers: [ { url: https://api.example.com } ]
security: [ { bearerAuth: [] } ]
components:
  securitySchemes: { bearerAuth: { type: http, scheme: bearer, bearerFormat: JWT } }
  responses:
    BadRequest: { $ref: './comm-common-errors.yaml#/components/responses/BadRequest' }
    Forbidden:  { $ref: './comm-common-errors.yaml#/components/responses/Forbidden' }
paths:
  /api/comm/calls:
    post:
      summary: Log phone call (manual entry)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [customerId, occurredAt, summary]
              properties:
                customerId: { type: string, format: uuid }
                occurredAt: { type: string, format: date-time }
                summary: { type: string, maxLength: 2000 }
                participants: { type: array, items: { type: string, format: email } }
      responses:
        '201': { description: Created }
        '400': { $ref: '#/components/responses/BadRequest' }
  /api/comm/meetings:
    post:
      summary: Log meeting notes (manual entry)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [customerId, occurredAt, summary]
              properties:
                customerId: { type: string, format: uuid }
                occurredAt: { type: string, format: date-time }
                summary: { type: string, maxLength: 5000 }
                attendees: { type: array, items: { type: string, format: email } }
      responses:
        '201': { description: Created }
        '400': { $ref: '#/components/responses/BadRequest' }
