openapi: 3.1.0
info: { title: Communication Common Errors, version: 1.0.0 }
components:
  schemas:
    Error:
      type: object
      required: [type, title, status]
      properties:
        type: { type: string }
        title: { type: string }
        status: { type: integer }
        detail: { type: string }
        errors:
          type: array
          items: { type: object, properties: { field: {type: string}, message: {type: string} } }
  responses:
    BadRequest: { description: Bad Request, content: { application/problem+json: { schema: { $ref: '#/components/schemas/Error' } } } }
    Forbidden:  { description: Forbidden,  content: { application/problem+json: { schema: { $ref: '#/components/schemas/Error' } } } }
    Conflict:   { description: Conflict,   content: { application/problem+json: { schema: { $ref: '#/components/schemas/Error' } } } }
    Precond:    { description: Precondition Failed,  content: { application/problem+json: { schema: { $ref: '#/components/schemas/Error' } } } }
