name: Admin ZAP Baseline
on:
  workflow_dispatch:

jobs:
  zap-baseline:
    runs-on: ubuntu-latest
    steps:
      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: 'https://staging.freshplan.example'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
