version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: freshplan-db
    environment:
      POSTGRES_DB: freshplan
      POSTGRES_USER: freshplan
      POSTGRES_PASSWORD: freshplan
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U freshplan"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Keycloak Identity Provider
  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    container_name: freshplan-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/freshplan
      KC_DB_USERNAME: freshplan
      KC_DB_PASSWORD: freshplan
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT: false
      KEYCLOAK_IMPORT: /tmp/freshplan-realm.json
    ports:
      - "8180:8080"
    volumes:
      - ./keycloak/freshplan-realm.json:/opt/keycloak/data/import/freshplan-realm.json
    depends_on:
      db:
        condition: service_healthy
    command: start-dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ready"]
      interval: 10s
      timeout: 5s
      retries: 10

  # Optional: pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: freshplan-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@freshplan.de
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    profiles:
      - tools

volumes:
  postgres_data:
    name: freshplan_postgres_data