openapi: 3.1.0
info: { title: Activities API (Module 03), version: 1.0.0 }
servers: [ { url: https://api.example.com } ]
security: [ { bearerAuth: [] } ]
components:
  securitySchemes: { bearerAuth: { type: http, scheme: bearer, bearerFormat: JWT } }
  schemas:
    ActivityKind: { type: string, enum: [PRODUCTTEST_FEEDBACK, ROI_CONSULTATION, MENU_INTEGRATION, DECISION_ALIGNMENT, TRAINING, QUALITY_CHECK] }
  responses:
    BadRequest: { $ref: './common-errors.yaml#/components/responses/BadRequest' }
    Forbidden:  { $ref: './common-errors.yaml#/components/responses/Forbidden' }
    Conflict:   { $ref: './common-errors.yaml#/components/responses/Conflict' }
    TooMany:    { $ref: './common-errors.yaml#/components/responses/TooMany' }
paths:
  /api/activities:
    post:
      summary: Aktivität anlegen
      responses: { '201': { description: Created }, '400': { $ref: '#/components/responses/BadRequest' } }
    get:
      summary: Aktivitäten suchen
      parameters:
        - { name: customerId, in: query, schema: { type: string, format: uuid } }
        - { name: kind, in: query, schema: { $ref: '#/components/schemas/ActivityKind' } }
        - { name: from, in: query, schema: { type: string, format: date-time } }
        - { name: to, in: query, schema: { type: string, format: date-time } }
      responses: { '200': { description: OK }, '403': { $ref: '#/components/responses/Forbidden' } }
