name: Backend Tests & Coverage

on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'
    paths:
      - 'backend/**'
      - '.github/workflows/backend-tests-coverage.yml'
  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/backend-tests-coverage.yml'

jobs:
  test:
    name: Run Backend Tests with Coverage
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: freshplan_test
          POSTGRES_USER: freshplan
          POSTGRES_PASSWORD: freshplan_test_pwd
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run tests with coverage
        run: ./mvnw verify -Dgroups="core" -Pcoverage
        continue-on-error: true
        env:
          QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://localhost:5432/freshplan_test
          QUARKUS_DATASOURCE_USERNAME: freshplan
          QUARKUS_DATASOURCE_PASSWORD: freshplan_test_pwd

      - name: Generate JaCoCo coverage report
        if: always()
        run: ./mvnw jacoco:report

      - name: Upload coverage to Codecov
        if: always()
        uses: codecov/codecov-action@v4
        with:
          files: ./backend/target/site/jacoco/jacoco.xml
          flags: backend
          name: backend-coverage
          fail_ci_if_error: false
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Archive coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage-report
          path: backend/target/site/jacoco/
          retention-days: 30

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-test-results
          path: backend/target/surefire-reports/
          retention-days: 7

      - name: Comment PR with coverage
        if: github.event_name == 'pull_request'
        uses: codecov/codecov-action@v4
        with:
          files: ./backend/target/site/jacoco/jacoco.xml
          flags: backend
          token: ${{ secrets.CODECOV_TOKEN }}
