name: CI - Integration Tests

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  backend-integration:
    name: Backend Integration Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    
    services:
      postgres:
        image: postgres:15-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: freshplan
          POSTGRES_USER: freshplan
          POSTGRES_PASSWORD: freshplan
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('backend/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      
      - name: Run integration tests
        run: mvn verify -DskipUnitTests
        env:
          KEYCLOAK_CLIENT_SECRET: ${{ secrets.KEYCLOAK_CLIENT_SECRET || 'secret' }}
          QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://localhost:5432/freshplan

  e2e-smoke:
    name: E2E Smoke Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    services:
      postgres:
        image: postgres:15-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: freshplan
          POSTGRES_USER: freshplan
          POSTGRES_PASSWORD: freshplan
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('backend/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      
      - name: Install frontend dependencies
        run: cd frontend && npm ci
      
      - name: Build frontend
        run: cd frontend && npm run build
      
      - name: Install Playwright
        run: cd frontend && npx playwright install --with-deps chromium
      
      - name: Start Backend (background)
        run: |
          # First ensure it's compiled
          mvn -B compile
          # Then start in dev mode with more logging
          mvn -B quarkus:dev -Dquarkus.http.host=0.0.0.0 > backend.log 2>&1 &
          # Give it time to start
          sleep 30
          # Show last 50 lines of log for debugging
          echo "=== Backend startup log ==="
          tail -n 50 backend.log || true
        working-directory: ./backend
        shell: bash
        env:
          KEYCLOAK_CLIENT_SECRET: secret
          QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://localhost:5432/freshplan
          QUARKUS_OIDC_ENABLED: false
          QUARKUS_SECURITY_USERS_EMBEDDED_ENABLED: true
      
      - name: Wait for Backend
        run: |
          echo "Waiting for backend to be ready..."
          for i in {1..30}; do
            if curl -f http://localhost:8080/q/health/ready 2>/dev/null; then
              echo "Backend is ready!"
              exit 0
            fi
            echo "Attempt $i/30 - Backend not ready yet..."
            sleep 2
          done
          echo "Backend failed to start!"
          # Show more logs for debugging
          echo "=== Full backend log ==="
          cat backend.log || true
          exit 1
        env:
          KEYCLOAK_CLIENT_SECRET: secret
      
      - name: Debug Backend Failure
        if: failure()
        run: |
          echo "=== Backend logs on failure ==="
          cd backend
          cat backend.log || true
          echo "=== Check if process is running ==="
          ps aux | grep quarkus || true
          echo "=== Check port 8080 ==="
          netstat -tlnp 2>/dev/null | grep 8080 || true
      
      - name: Run Playwright tests
        run: |
          cd frontend
          # Set API URL for tests
          export VITE_API_URL=http://localhost:8080
          npx playwright test --project=chromium
      
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: frontend/playwright-report/
          retention-days: 30
      
      - name: Cleanup
        if: always()
        run: |
          pkill -f quarkus:dev || true

  integration-success:
    name: Integration Tests Success
    needs: [backend-integration, e2e-smoke]
    runs-on: ubuntu-latest
    steps:
      - name: All integration tests passed
        run: echo "✅ All integration tests passed!"