name: CI - Lint & Format Check

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lint-frontend:
    name: Lint Frontend (React)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run ESLint
        run: npm run lint
      
      - name: Check TypeScript
        run: npm run type-check
      
      - name: Check Prettier formatting
        run: npm run format:check

  lint-backend:
    name: Lint Backend (Quarkus)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      
      - name: Run Checkstyle
        run: ./mvnw checkstyle:check
      
      - name: Run SpotBugs
        run: ./mvnw spotbugs:check
      
      - name: Check formatting
        run: ./mvnw formatter:validate

  lint-legacy:
    name: Lint Legacy Code
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./legacy
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: legacy/package-lock.json
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run ESLint
        run: npm run lint
        continue-on-error: true # Legacy code may have existing issues
      
      - name: Check TypeScript
        run: npm run check

  quality-gate:
    name: Quality Gate Check
    needs: [lint-frontend, lint-backend, lint-legacy]
    runs-on: ubuntu-latest
    
    steps:
      - name: All checks passed
        run: echo "✅ All linting checks passed!"