name: Database Growth Check Debug

on:
  push:
    branches: [ feat/* ]

env:
  ACTIONS_RUNNER_DEBUG: true
  ACTIONS_STEP_DEBUG: true

jobs:
  check-database-growth:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: freshplan
          POSTGRES_PASSWORD: freshplan
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U freshplan"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
    - name: Debug - Workflow Started
      run: |
        echo "===================================="
        echo "WORKFLOW STARTED SUCCESSFULLY"
        echo "===================================="
        echo "GitHub Run ID: ${{ github.run_id }}"
        echo "GitHub Job: ${{ github.job }}"
        echo "Runner OS: ${{ runner.os }}"
        echo "Current directory: $(pwd)"

    - name: Simple Test Echo
      run: echo "THIS SHOULD APPEAR IN LOGS"

    - name: Check PostgreSQL
      env:
        PGPASSWORD: freshplan
      run: |
        echo "Installing PostgreSQL client..."
        sudo apt-get update && sudo apt-get install -y postgresql-client
        echo "Testing connection..."
        psql -h localhost -p 5432 -U freshplan -d postgres -c "SELECT 1;"
        echo "PostgreSQL connection successful!"