name: Debug Backend Simple

on:
  push:
    branches: [feature/user-management]
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          
      - name: Show versions
        run: |
          echo "=== Java Version ==="
          java -version
          echo "=== Maven Version ==="
          mvn -version
          
      - name: List files
        run: |
          echo "=== Backend structure ==="
          ls -la backend/
          echo "=== Source files ==="
          find backend/src -name "*.java" | wc -l
          
      - name: Compile
        run: mvn clean compile
        working-directory: backend
        
      - name: Run tests
        run: mvn test
        working-directory: backend