name: Debug Backend Build

on:
  push:
    branches: [feature/user-management]
  workflow_dispatch:

jobs:
  debug-backend:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
          
      - name: Show Java version
        run: java -version
        
      - name: Fix mvnw permissions and show Maven version
        run: |
          chmod +x mvnw
          sh ./mvnw -version
        working-directory: backend
        
      - name: List backend source files
        run: |
          echo "=== Source files ==="
          find src/main/java -name "*.java" | head -20
          echo "=== Test files ==="
          find src/test/java -name "*.java" | head -20
        working-directory: backend
        
      - name: Show pom.xml dependencies
        run: |
          echo "=== Dependencies ==="
          sh ./mvnw dependency:tree | grep -E "(hibernate-validator|mockito|junit)" || true
        working-directory: backend
        
      - name: Compile main sources with debug
        run: sh ./mvnw compile -X
        working-directory: backend
        continue-on-error: true
        
      - name: Compile test sources with debug
        run: sh ./mvnw test-compile -X
        working-directory: backend
        continue-on-error: true
        
      - name: Run single test with debug
        run: |
          echo "=== Running UserMapperTest ==="
          sh ./mvnw test -Dtest=UserMapperTest -X
        working-directory: backend
        continue-on-error: true
        
      - name: Check for missing imports
        run: |
          echo "=== Checking imports in test files ==="
          grep -n "import.*mockito" src/test/java/**/*.java || echo "No mockito imports found"
          grep -n "InjectMock" src/test/java/**/*.java || echo "No InjectMock found"
        working-directory: backend