name: Docs-Only Guardrail

on:
  pull_request:
    types: [opened, synchronize]
    branches: [main, develop]

jobs:
  check-docs-only:
    runs-on: ubuntu-latest
    if: contains(github.head_ref, 'research') || contains(github.head_ref, 'docs')

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files_ignore: |
            docs/**
            *.md
            .github/workflows/docs-only-check.yml
            CLAUDE.md
            README.md
            TRIGGER*.md

      - name: Check for non-docs changes
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          echo "❌ ERROR: Research/Docs branches should only contain documentation changes!"
          echo "Found non-documentation changes in:"
          echo "${{ steps.changed-files.outputs.all_changed_files }}"
          echo ""
          echo "This PR is marked as research/documentation only."
          echo "Please move code changes to a separate feature branch."
          exit 1

      - name: Success - Docs only
        if: steps.changed-files.outputs.any_changed == 'false'
        run: |
          echo "✅ SUCCESS: Only documentation files changed"
          echo "This PR contains documentation changes only, as expected."