name: Backend/Frontend Field Parity Check

on:
  pull_request:
    paths:
      - 'frontend/src/features/customers/data/fieldCatalog.json'
      - 'backend/src/main/java/de/freshplan/domain/customer/entity/Customer.java'
      - 'backend/src/main/java/de/freshplan/domain/customer/entity/CustomerLocation.java'
  push:
    branches:
      - main
      - 'feat/**'
      - 'fix/**'
    paths:
      - 'frontend/src/features/customers/data/fieldCatalog.json'
      - 'backend/src/main/java/de/freshplan/domain/customer/entity/Customer.java'
      - 'backend/src/main/java/de/freshplan/domain/customer/entity/CustomerLocation.java'

jobs:
  parity-check:
    name: Field Parity Validation
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Run Field Parity Check
        run: |
          echo "🔍 Validating Backend/Frontend Field Parity..."
          python3 scripts/check-field-parity.py
        
      - name: Comment PR on failure
        if: failure() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '## ❌ Backend/Frontend Field Parity Check Failed\n\n' +
                    'Ghost fields detected in `fieldCatalog.json`!\n\n' +
                    '**Action required:**\n' +
                    '1. Remove ghost fields from `fieldCatalog.json`, OR\n' +
                    '2. Add missing fields to backend entities (+ migration)\n\n' +
                    'See workflow logs for details.\n\n' +
                    '📖 Reference: `CLAUDE.md` → BACKEND/FRONTEND PARITY'
            })
