name: Frontmatter Lint
on:
  pull_request:
    paths:
      - 'docs/**/*.md'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: pip install pyyaml
      - name: Run lint
        run: python .github/scripts/frontmatter_lint.py