name: Mini E2E

on:
  push:
    branches:
      - ci-minimal-working
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Max 10 minutes
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build
        run: npm run build:ci
      
      - name: Install Playwright Chromium only
        run: |
          npx playwright install chromium
          npx playwright install-deps chromium
      
      - name: Run minimal tests
        run: npx playwright test healthcheck customer-phase2-basic-mini backup-smoke --config=playwright.config.minimal.ts
      
      - name: Upload results on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            playwright-report/
            test-results/
          retention-days: 3