name: Mini E2E

on:
  push:
    branches:
      - ci-minimal-working
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Max 10 minutes
    strategy:
      matrix:
        browser: [chromium, firefox]
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      
      - name: Install dependencies
        run: cd frontend && npm ci
      
      - name: Build
        run: cd frontend && npm run build
      
      - name: Install Playwright ${{ matrix.browser }}
        run: |
          cd frontend
          npx playwright install ${{ matrix.browser }}
          npx playwright install-deps ${{ matrix.browser }}
      
      - name: Run tests on ${{ matrix.browser }}
        run: cd frontend && npx playwright test --project=${{ matrix.browser }}
        continue-on-error: false
      
      - name: Upload results on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.browser }}
          path: |
            playwright-report/
            test-results/
          retention-days: 3
      
      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ matrix.browser }}
          path: playwright-report/
          retention-days: 7