name: Smoke Tests

on:
  pull_request:
  workflow_dispatch:

jobs:
  playwright:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json
      
      - name: Install dependencies
        run: cd frontend && npm ci
      
      - name: Build application
        run: |
          cd frontend
          echo "🔨 Building frontend application..."
          npm run build
          echo "✅ Build completed. Checking build output:"
          ls -la dist/ | head -10
          echo "Index.html content preview:"
          head -20 dist/index.html || echo "index.html not found"
      
      - name: Install Playwright
        run: cd frontend && npx playwright install --with-deps chromium
      
      - name: Run Playwright tests
        run: |
          cd frontend
          echo "🎭 Starting Playwright tests with debug output..."
          echo "Current directory: $(pwd)"
          echo "Files in dist folder:"
          ls -la dist/ || echo "dist folder not found"
          echo "Running tests..."
          DEBUG=pw:api npx playwright test --project=chromium --reporter=list
        env:
          CI: true
          DEBUG: pw:api,pw:browser
      
      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: frontend/playwright-report/
          retention-days: 7
      
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-traces
          path: |
            frontend/test-results/
            frontend/playwright-report/
          retention-days: 7