name: Structure Guard (Modules)
on:
  pull_request:
    paths:
      - 'docs/planung/features-neu/**'
jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Enforce module root rule
        shell: bash
        run: |
          fail=0
          for ROOT in docs/planung/features-neu/*_*; do
            [ -d "$ROOT" ] || continue
            mapfile -t items < <(ls -1 "$ROOT" | grep -v '^\.' || true)

            # Stub-Verzeichnisse (haben _index.md mit doc_type: "stub")
            stub_dirs=()
            for d in "${items[@]}"; do
              if [ -d "$ROOT/$d" ] && [ -f "$ROOT/$d/_index.md" ] && grep -q 'doc_type: *"stub"' "$ROOT/$d/_index.md"; then
                stub_dirs+=("$d")
              fi
            done

            # Zählmenge = alle Items minus Stub-Verzeichnisse
            count=$(
              for d in "${items[@]}"; do
                skip=0
                for s in "${stub_dirs[@]}"; do [ "$d" = "$s" ] && skip=1 && break; done
                [ $skip -eq 0 ] && echo "$d"
              done | wc -l
            )

            legacy=0
            [ -d "$ROOT/legacy-planning" ] && legacy=1

            # Regel: <= 8 Kern-Items (+1 falls legacy-planning vorhanden)
            if [ $count -gt $((8 + legacy)) ]; then
              echo "::error file=$ROOT::Root enthält $count Items (Stub-Ordner ausgenommen). Erlaubt: 8 + legacy-planning"
              fail=1
            fi
          done
          exit $fail