name: Update Documentation

on:
  push:
    paths:
      - 'WAY_OF_WORKING.md'
      - '.github/workflows/update-docs.yml'
  workflow_dispatch:

jobs:
  update-html:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Update HTML version
        run: |
          echo "Note: HTML is manually maintained for better control"
          echo "Please update WAY_OF_WORKING.html when changing WAY_OF_WORKING.md"
      
      - name: Check if files are in sync
        run: |
          # Extract key sections from markdown
          MD_CHECKSUM=$(grep -E "^(#|##|###|\||Sprint)" WAY_OF_WORKING.md | md5sum | cut -d' ' -f1)
          echo "Markdown structure checksum: $MD_CHECKSUM"
          
          # This is a reminder to keep both files in sync
          echo "::warning::Remember to update WAY_OF_WORKING.html when changing the markdown!"